### ISSUE TITLE
Recovery hook

### ISSUE THREAD

**Issue by kuzvaleir** [btbd/umap#8]
Im started learning this code, and found some post about wrong recovery hook. Just want to show it for you. If its wrong nevermind.

When executes here, rip is the original entry address of acpiex.sys. Why should we subtract 7? Finally, after jumping to the entry of our mapper module, r8 happens to be the original entry address, but mapperData also saves the entry address of the acpiex.sys , so its recovery hook is meaningless and completely messed up.

Code #1:

    MemCopy(targetModule->EntryPoint, "\x4C\x8D\x05\xF9\xFF\xFF\xFF", 7);

Code #2:

    UINT8 *mapperData = FindPattern(mapperBuffer + section->PointerToRawData, section->SizeOfRawData, "\x12\x34\x56\x78\x90", L"xxxxx");
    			if (mapperData) {
    				MemCopy(mapperData, targetFunction, MAPPER_DATA_SIZE);
    			}

Code #3:

    static volatile BYTE mapperData[MAPPER_DATA_SIZE] = { 0x12, 0x34, 0x56, 0x78, 0x90 };
     
    	// Undo hook by bootkit (no error checking because there's no reason it should fail
    	// and if it does fail then you can't recover)
    	MemCopyWP(func, (PVOID)mapperData, sizeof(mapperData));

**Comment by btbd** [comment]
@kuzvaleir 

1. RIP-relative instructions use the value of RIP of the next instruction. The length of the instruction is 7 bytes, so we must subtract 7.

![image](https://user-images.githubusercontent.com/22239674/86134491-afd56200-bab7-11ea-980e-409846204916.png)

![image](https://user-images.githubusercontent.com/22239674/86134501-b4017f80-bab7-11ea-9671-e115e580d04c.png)

2. That code copies the original bytes of the entrypoint into `mapperData`, not the address of the entrypoint.
3. Since `mapperData` holds the original bytes of the entrypoint, not its address, that code simply undoes the entrypoint hook.

**Comment by kuzvaleir** [comment]
ok thanks for explanation
